import pytest
from sssm import SimpleStockDataSimulator

COLUMNS = [
    "time",
    "ticker",
    "type",
    "last_price",
    "dividend",
    "fixed_dividend",
    "par_value",
    "transaction_type",
    "quantity",
]


class TestSimulatorClass:
    def test_init(self):
        simulator = SimpleStockDataSimulator(COLUMNS)
        assert (
            simulator.fields == COLUMNS
        ), "Fields in the class are not the same as the columns specified."

    def test_headers(self):
        simulator = SimpleStockDataSimulator(COLUMNS)
        assert all(
            simulator.data.columns == COLUMNS
        ), "Columns of the dataframe are not specified appropriately."

    def test_generate_data(self):
        simulator = SimpleStockDataSimulator(COLUMNS)

        df = simulator.generate_data(15)

        assert len(df) >= 0, "No data has been generated by the simulator"
        assert df.index.inferred_type == "datetime64", "Time is not a datetime"
